# Create the Flora environment:
# mamba env create -f environment.yml 
# or 
# conda env create -f environment.yml

name : flora
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - cdo
  - netcdf4
  - xarray
  - ipykernel
  - zarr
  - dask
  - pip
  - pip:
    - cdsapi
    - ecmwf-api-client
    - cdo
